version: '3.4'
services:

  mysql:
    image: 'mysql:5.7'
    ports:
      - '3306:3306'
    volumes:
      - './.data/db:/var/lib/mysql'
      - './docker/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf'
      - './docker/mysql/admin.sql:/docker-entrypoint-initdb.d/admin.sql'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'

  php-fpm:
    build:
      context: docker/php-fpm
      args:
        - 'INSTALL_OPCACHE=${INSTALL_OPCACHE}'
        - 'INSTALL_XDEBUG=${INSTALL_XDEBUG}'
        - 'UID=${UID}'
    environment:
      XDEBUG_CONFIG: remote_host=192.168.220.1 remote_enable=1
      PHP_IDE_CONFIG: serverName=Docker
    volumes:
      - '${APP_PATH}:/var/www/html'
    depends_on:
      - redis

  web:
    image: 'nginx:latest'
    depends_on:
      - php-fpm
    ports:
      - '${APP_PORT}:80'
    volumes:
      - './project:/var/www/html'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'

  redis:
    image: 'redis:latest'
